# -*- coding: utf-8 -*-
"""
claim_ranking.py — the algorithm that separates and ranks claim documents, as plain Python.

This is a line-for-line port of the web app's engine (Week 3-4/mvp/backend/engine/{existing.js, rules.js, store.js}):
same rules, same parameters, same arithmetic, so the notebook reproduces the numbers shown in the app.

Pipeline for every incoming claim, in submission order
    1. Engine 1  — the openIMIS edits (reasons 9, 21, 2, 10, 16) on the claim alone → accepted / rejected
    2. Identity  — National ID if present, else name + date of birth + sex  → an identity key
    3. History   — every earlier claim of the same identity (both schemes, all facilities) + provider context
    4. Rules     — R1–R5 per earlier claim, R8 and STG per claim, R7 per doctor, R6 per facility → flags with a reason
    5. Scoring   — subsumption (R4 under R3), points = learned weight × confidence, suspicion = Σ points
    6. Routing   — any flag → review queue (status Selected), else clean → payment
    7. Ranking   — the queue is ordered by suspicion; the reviewer budget is 5 % of the book (today's random sample)
    8. Learning  — confirm / clear / release moves the rule's weight by ±0.5, bounded 0.5 … 5

All data is synthetic (generated by Week 3-4/synthetic_data/*.py). No real patient or claim data anywhere.
"""
from __future__ import annotations
import json, math, random, re, time
from dataclasses import dataclass, field
from datetime import date

# ----------------------------------------------------------------------------- constants (rules.js)
FRAUD = {'within_dup', 'same_episode', 'cross_scheme', 'impossible_overlap', 'resubmission', 'stg_upcode',
         'phantom_readmission', 'upcode_within_protocol', 'phantom_visit'}
# services that legitimately repeat — never evidence on their own
REPEATABLE = {'DIALYSIS', 'CHEMO-CYCLE', 'WARD-DAY', 'ICU-DAY', 'DRUGS-IPD', 'IV-FLUIDS', 'OXYGEN-DAY', 'CONS-OPD'}
QTY_HARD_CAP = 30

RULES = {
    'R1':  dict(name='Within-scheme duplicate (same day, or identical bill within 14 days)', weight='high',
                source='rule catalog R1 · openIMIS reason 6 (disabled) · validation book: re-bills lag 0–14 d'),
    'R2':  dict(name='Same-episode split billing (vault)', weight='medium',
                source='rule catalog R2 · SSF claim vault (facility + contributor + visit date)'),
    'R3':  dict(name='Cross-scheme duplicate (HIB ↔ SSF)', weight='high',
                source='rule catalog R3 · independent ledgers · composite identity → medium'),
    'R4':  dict(name='Overlapping inpatient stays (transfer-aware)', weight='high',
                source='rule catalog R4 · "impossible day" · report: ghost / phantom hospitalisation'),
    'R5':  dict(name='Resubmission gaming (new code after a rejection)', weight='medium',
                source='rule catalog R5 · edit-gaming attack surface · validation book: honest corrections'),
    'STG': dict(name='Off-protocol services, over-long stay or unnecessary admission', weight='medium',
                source='HIB expert interview: standard treatment protocol · reason 8 (ICD) disabled · report: medical necessity'),
    'R6':  dict(name='Provider concentration (facility flag rate far above peers)', weight='low',
                source='report: peer benchmarking, PM-JAY provider profiling and de-empanelment'),
    'R7':  dict(name='One doctor, two facilities, same day', weight='low',
                source='ontology red flag rfSameProviderManyFacilities · report: ghost hospitalisation, duty-hour billing'),
    'R8':  dict(name='Service frequency beyond what the diagnosis warrants', weight='medium',
                source='report: unnecessary tests (HIB 10 % co-payment, Jan 2024) · Taiwan NHI duplicate-service check · HIRA DUR'),
}


@dataclass
class Params:
    """Every tunable of the algorithm in one place (defaults = the app)."""
    weights: dict = field(default_factory=lambda: {'high': 3, 'medium': 2, 'low': 1})
    r3_window_days: int = 2      # the same episode is often claimed in the other scheme a day or two later
    r1_near_days: int = 14       # identical line set re-billed within two weeks
    r5_lookback_days: int = 14   # resubmissions lag 1–14 d
    r8_window_days: int = 30
    r6_min_claims: int = 20
    r6_rate_factor: float = 3.0
    r6_min_rate: float = 0.25
    facility_window: int = 100   # rolling window of claims per facility for R6
    doctor_window: int = 40      # last claims per NMC number for R7
    budget_share: float = 0.05   # reviewer budget = today's 5 % random sample
    enabled: frozenset | None = None   # None = every rule; else the subset of rule ids that may fire
    learn_delta: float = 0.5     # reviewer feedback: confirm +δ, clear −δ
    weight_bounds: tuple = (0.5, 5.0)


# ----------------------------------------------------------------------------- helpers
def _d(s: str) -> date:
    return date.fromisoformat(s)

def days(a: str, b: str) -> int:
    return (_d(a) - _d(b)).days

def jround(x: float, nd: int = 0) -> float:
    """JavaScript Math.round semantics (half away from zero for positives)."""
    m = 10 ** nd
    return math.floor(x * m + 0.5) / m

def identity_key(p: dict) -> dict:
    if p.get('national_id'):
        return {'kind': 'NID', 'key': 'NID:' + p['national_id']}
    norm = ' '.join(str(p.get('name') or '').lower().split())
    return {'kind': 'COMPOSITE', 'key': f"COMP:{norm}|{p.get('dob')}|{p.get('sex')}"}

def overlaps(a: dict, b: dict, window: int = 0) -> bool:
    aF, aT = _d(a['date_from']), _d(a.get('date_to') or a['date_from'])
    bF, bT = _d(b['date_from']), _d(b.get('date_to') or b['date_from'])
    return (aF - bT).days <= window and (bF - aT).days <= window

def codes(c: dict) -> set:
    return {l['code'] for l in (c.get('lines') or [])}

def los(c: dict) -> int:
    return days(c.get('date_to') or c['date_from'], c['date_from'])

def freq_limit(code: str) -> int:
    if code == 'CONS-OPD': return 4
    if re.match(r'^(CT|MRI|USG|XRAY|ECHO|ECG)', code): return 2
    if code.startswith('LAB'): return 3
    return 3


# ----------------------------------------------------------------------------- ENGINE 1 — openIMIS edits (existing.js)
def validate_existing(claim: dict, ref: dict) -> dict:
    """A faithful slice of openIMIS validate_claim: each edit looks at the claim alone.
    Reason 6 (DUPLICATED) and 8 (ICD_NOT_IN_LIST) are commented out in the real source; reason 5 never runs."""
    d_from, d_to = claim['date_from'], claim.get('date_to') or claim['date_from']
    if d_to < d_from:
        return dict(accepted=False, code=9, reason='TARGET_DATE', because='discharge date precedes admission date')
    if not claim.get('policy_active', True):
        return dict(accepted=False, code=21, reason='NO_COVERAGE', because=f"no active {claim['scheme']} policy covers this person on {d_from}")
    off = [l['code'] for l in claim.get('lines') or [] if l['code'] not in ref['price_list']]
    if off:
        return dict(accepted=False, code=2, reason='NOT_IN_PRICE_LIST', because=f"'{off[0]}' is not in the facility price list")
    fac = ref['facilities'].get(claim['facility_id'])
    if fac and fac.get('care') == 'O' and claim['care_type'] == 'I':
        return dict(accepted=False, code=10, reason='CARE_TYPE', because=f"{fac['name']} is outpatient-only but the claim is inpatient")
    over = next((l for l in claim.get('lines') or [] if l['qty'] > QTY_HARD_CAP), None)
    if over:
        return dict(accepted=False, code=16, reason='QTY_OVER_LIMIT', because=f"quantity {over['qty']} of {over['code']} exceeds the cap {QTY_HARD_CAP}")
    return dict(accepted=True, code=0, reason='ACCEPTED', because='every active edit passed — the claim is CHECKED and moves on')


# ----------------------------------------------------------------------------- ENGINE 2 — the rules (rules.js)
def match_rules(claim: dict, history: list, ref: dict, ctx: dict | None = None, P: Params = Params()) -> list:
    """Compare the incoming claim with the person's claim HISTORY (across facilities and schemes) and with the
    provider context; return weighted, explained flags. Never rejects.

    history : [{'claim': prior claim, 'verdict': engine-1 verdict}] for the same identity, oldest first
    ref     : {'protocol': {dx: {'allow': set, 'max_los': int, 'ipd': float, 'label': str}}, ...}
    ctx     : {'facility': {'claims', 'flagged', 'medianRate'} | None, 'doctorClaims': [claims with the same NMC no.]}
    """
    ctx = ctx or {}
    flags: list = []

    def flag(rule, matched, because, weight=None):
        flags.append(dict(rule=rule, name=RULES[rule]['name'], weight=weight or RULES[rule]['weight'],
                          source=RULES[rule]['source'], claim_id=claim['claim_id'], matched=matched, because=because))

    cc = codes(claim)
    non_repeat = [x for x in cc if x not in REPEATABLE]
    proto = ref['protocol'].get(claim['diagnosis'])
    # dialysis / chemotherapy protocols legitimately repeat the same bill every few days
    repeat_dx = bool(proto) and any(x in ('DIALYSIS', 'CHEMO-CYCLE') for x in proto['allow'])

    for h in history:
        prev, verdict = h['claim'], h['verdict']
        pc = codes(prev); shared = [x for x in pc if x in cc]; gap = abs(days(claim['date_from'], prev['date_from']))

        # R1 — same person, same scheme, same date, a shared service (high); or the identical bill re-entered within 14 days (medium)
        if prev['scheme'] == claim['scheme'] and prev['date_from'] == claim['date_from'] and shared:
            flag('R1', prev['claim_id'], f"same person, same scheme ({claim['scheme']}), same date ({claim['date_from']}) and a shared service "
                 f"[{', '.join(shared)}] as {prev['claim_id']} — one service cannot be billed twice.")
        elif (not repeat_dx and prev['scheme'] == claim['scheme'] and 0 < gap <= P.r1_near_days and non_repeat
              and pc == cc and prev['diagnosis'] == claim['diagnosis']):
            flag('R1', prev['claim_id'], f"the same bill as {prev['claim_id']} ({', '.join(sorted(cc))}, {claim['diagnosis']}) re-entered {gap} day(s) "
                 f"later under a new claim code — a re-billed visit, unless the treatment genuinely repeats.", 'medium')
        # R2 — same person, same facility, same visit date, different lines (the SSF vault key)
        elif prev['scheme'] == claim['scheme'] and prev['facility_id'] == claim['facility_id'] and prev['date_from'] == claim['date_from']:
            flag('R2', prev['claim_id'], f"same person, same facility ({claim['hf_name']}) and same visit date ({claim['date_from']}) as {prev['claim_id']}, "
                 f"but different lines — one episode possibly split into two claims.")
        # R3 — different scheme, overlapping dates (±window), same diagnosis or a shared service; weight follows identity confidence
        if prev['scheme'] != claim['scheme'] and overlaps(prev, claim, P.r3_window_days) and (prev['diagnosis'] == claim['diagnosis'] or shared):
            idk = identity_key({'name': claim['person_name'], 'dob': claim['dob'], 'sex': claim['sex'], 'national_id': claim.get('national_id')})
            flag('R3', prev['claim_id'], f"same person (matched on {'National ID' if idk['kind'] == 'NID' else 'composite key: name + DOB + sex — could be a namesake'}) "
                 f"with the same diagnosis/service within {P.r3_window_days} days of {prev['claim_id']}, but a DIFFERENT scheme ({prev['scheme']} vs {claim['scheme']}) "
                 f"— neither system sees the other today.", None if idk['kind'] == 'NID' else 'medium')
        # R4 — two inpatient stays overlapping: different facilities (unless a same-day transfer) or the same facility (phantom re-admission)
        if claim['care_type'] == 'I' and prev['care_type'] == 'I' and overlaps(prev, claim):
            transfer = (prev['facility_id'] != claim['facility_id'] and prev['diagnosis'] == claim['diagnosis']
                        and (prev.get('date_to') == claim['date_from'] or claim.get('date_to') == prev['date_from']))
            if transfer:
                pass  # discharged here, admitted there the same day: a referral, not an impossibility
            elif prev['facility_id'] != claim['facility_id']:
                flag('R4', prev['claim_id'], f"admission {claim['date_from']}..{claim.get('date_to')} at {claim['hf_name']} overlaps the inpatient stay "
                     f"{prev['date_from']}..{prev.get('date_to')} at {prev['hf_name']} ({prev['claim_id']}) — a patient cannot be admitted in two places at once.")
            else:
                flag('R4', prev['claim_id'], f"a second inpatient stay {claim['date_from']}..{claim.get('date_to')} at {claim['hf_name']} overlaps the stay "
                     f"{prev['date_from']}..{prev.get('date_to')} already billed by the same facility ({prev['claim_id']}) — one admission billed twice, or a phantom re-admission.", 'medium')
        # R5 — a prior REJECTED claim, same diagnosis, within 14 days, and the new claim INTRODUCES a code the rejected one did not have
        if verdict and not verdict['accepted'] and prev['diagnosis'] == claim['diagnosis'] and gap <= P.r5_lookback_days:
            introduced = [x for x in cc if x not in pc]
            if introduced:
                flag('R5', prev['claim_id'], f"resembles {prev['claim_id']}, which was rejected (reason {verdict['code']} {verdict['reason']}) {gap} day(s) earlier "
                     f"for the same diagnosis, and now carries a code it did not have [{', '.join(introduced)}] — a swap to get past the edit.")

    # R8 — the same service for the same person more often in 30 days than the diagnosis warrants
    for code in ([] if repeat_dx else non_repeat):
        n = sum(1 for h in history if code in codes(h['claim']) and abs(days(claim['date_from'], h['claim']['date_from'])) <= P.r8_window_days)
        if n >= freq_limit(code):
            flag('R8', None, f"{code} billed {n + 1} times for this person in {P.r8_window_days} days (limit {freq_limit(code)}) — repeated tests or visits beyond what {claim['diagnosis']} warrants.")
            break

    # STG — standard-treatment-protocol conformance (per claim; openIMIS has no diagnosis check)
    if proto:
        off = sorted(x for x in cc if x not in proto['allow'])
        if off:
            flag('STG', None, f"diagnosis {claim['diagnosis']} ({proto['label']}) does not warrant [{', '.join(off)}] under the standard treatment protocol — a possible upcode / unbundling.")
        elif claim['care_type'] == 'I' and proto['ipd'] == 0:
            flag('STG', None, f"{claim['diagnosis']} ({proto['label']}) is an outpatient condition under the protocol, yet this is an inpatient admission — unnecessary hospitalisation.")
        elif los(claim) > proto['max_los']:
            flag('STG', None, f"length of stay {los(claim)} days exceeds the typical {proto['max_los']} for {claim['diagnosis']} ({proto['label']}).")

    # R7 — the treating doctor's NMC number is on another facility's claim on the same day(s)
    for other in ctx.get('doctorClaims') or []:
        if other['facility_id'] != claim['facility_id'] and overlaps(other, claim):
            flag('R7', other['claim_id'], f"NMC {claim.get('nmc_no')} is the treating doctor on {other['claim_id']} at {other['hf_name']} on the same day(s) ({other['date_from']}) — one doctor billing from two facilities at once.")
            break

    # R6 — the facility's flag rate is far above its peers (only once there is enough history to judge)
    f = ctx.get('facility')
    if f and f['claims'] >= P.r6_min_claims and f['medianRate'] > 0 and f['flagged'] / f['claims'] >= P.r6_min_rate and f['flagged'] / f['claims'] > P.r6_rate_factor * f['medianRate']:
        flag('R6', None, f"{claim['hf_name']} has had {f['flagged']} of its last {f['claims']} claims flagged ({100 * f['flagged'] / f['claims']:.0f} %, peers {100 * f['medianRate']:.0f} %) "
             f"— fraud clusters in a few providers, so every claim from here deserves a closer look.")

    if P.enabled is not None:
        flags = [x for x in flags if x['rule'] in P.enabled]
    # subsumption: an R4 overlap against the same matched claim as an R3 cross-scheme hit is the same event seen twice
    r3 = {x['matched'] for x in flags if x['rule'] == 'R3'}
    for x in flags:
        if x['rule'] == 'R4' and x['matched'] in r3:
            x['subsumedBy'] = 'R3'
    return flags


# ----------------------------------------------------------------------------- the claim book (store.js)
class Engine:
    """Runs both engines over a claim book in submission order and keeps the state the rules need:
    the identity index (claim history), the facility flag-rate window (R6), the doctor index (R7) and the learned weights."""

    STATUS = dict(REJECTED=1, ENTERED=2, CHECKED=4, PROCESSED=8, VALUATED=16)

    def __init__(self, data: dict, params: Params = Params(), verbose: bool = True):
        self.P = params
        self.meta = data['meta']
        self.price_list = data['price_list']
        self.protocol = {k: {**v, 'allow': set(v['allow'])} for k, v in data['protocol'].items()}
        self.facilities = {f['hf_id']: f for f in data['facilities']}
        self.persons = {p['insuree_id']: p for p in data['persons']}
        self.ref = dict(price_list=self.price_list, protocol=self.protocol, facilities=self.facilities)
        self.claims: list = []
        self.by_id: dict = {}
        self.index: dict = {}            # identity key -> [{'claim', 'verdict'}]
        self.rule_weight = {r: params.weights[x['weight']] for r, x in RULES.items()}
        self.weight_log: list = []
        self.fac_stats: dict = {}        # facility_id -> {'recent': [0/1 ...]}
        self.by_doctor: dict = {}        # nmc_no -> [claims]
        self.median_rate = 0.0; self._median_at = 0
        t0 = time.time()
        for c in data['claims']:
            self.process(dict(c))
        self.seconds = time.time() - t0
        if verbose:
            print(f"[engine] {len(self.claims)} claims processed in {self.seconds:.1f} s · {sum(1 for c in self.claims if c['flags'])} flagged")

    # ---- the two engines, in order
    def process(self, c: dict) -> dict:
        P = self.P
        c['lines'] = c.get('lines') or []
        c['engine1'] = validate_existing(c, self.ref)
        idk = identity_key({'name': c['person_name'], 'dob': c['dob'], 'sex': c['sex'], 'national_id': c.get('national_id')})
        c['identity'] = idk
        hist = self.index.get(idk['key'], [])
        c['history_size'] = len(hist)
        if c['engine1']['accepted']:
            c['status'] = self.STATUS['CHECKED']
            fs = self.fac_stats.get(c['facility_id'])
            ctx = dict(facility=(dict(claims=len(fs['recent']), flagged=sum(fs['recent']), medianRate=self.median_rate) if fs else None),
                       doctorClaims=self.by_doctor.get(c.get('nmc_no'), []) if c.get('nmc_no') else [])
            flags = match_rules(c, hist, self.ref, ctx, P)
            # points = the rule's current (learned) weight, scaled when the flag carries a lower confidence (e.g. R3 on a composite identity)
            for f in flags:
                f['points'] = 0 if f.get('subsumedBy') else jround(self.rule_weight[f['rule']] * P.weights[f['weight']] / P.weights[RULES[f['rule']]['weight']], 1)
            c['flags'] = flags
            c['suspicion'] = jround(sum(f['points'] for f in flags), 1)
            c['routed'] = 'review' if flags else 'payment'
        else:
            c['status'] = self.STATUS['REJECTED']; c['rejection_reason'] = c['engine1']['code']; c['flags'] = []; c['suspicion'] = 0; c['routed'] = 'rejected'
        # remember everything (a rejected claim is exactly what R5 looks back to)
        self.index.setdefault(idk['key'], []).append({'claim': c, 'verdict': c['engine1']})
        self.claims.append(c); self.by_id[c['claim_id']] = c
        # provider context for R6 / R7
        fs = self.fac_stats.setdefault(c['facility_id'], {'recent': []})
        strong = any(not f.get('subsumedBy') and f['rule'] not in ('R6', 'R7') for f in c['flags'])
        fs['recent'].append(1 if strong else 0)
        if len(fs['recent']) > P.facility_window: fs['recent'].pop(0)
        if len(self.claims) - self._median_at >= 250:
            rates = sorted(sum(x['recent']) / len(x['recent']) for x in self.fac_stats.values() if len(x['recent']) >= 20)
            self.median_rate = rates[len(rates) // 2] if rates else 0.0; self._median_at = len(self.claims)
        if c.get('nmc_no'):
            arr = self.by_doctor.setdefault(c['nmc_no'], []); arr.append(c)
            if len(arr) > P.doctor_window: arr.pop(0)
        return c

    def amount(self, c: dict) -> float:
        return sum(self.price_list.get(l['code'], 0) * l['qty'] for l in c.get('lines') or [])

    # ---- the review queue
    @property
    def budget(self) -> int:
        return max(1, int(jround(self.P.budget_share * len(self.claims))))

    def ranked(self, limit: int | None = None) -> list:
        """The queue: flagged, un-reviewed claims in decreasing suspicion (stable → submission order breaks ties)."""
        pool = [c for c in self.claims if c['status'] == self.STATUS['CHECKED'] and not c.get('review')]
        q = sorted((c for c in pool if c['flags']), key=lambda c: -c['suspicion'])
        return q[:limit] if limit else q

    def random_sample(self, seed: int, budget: int | None = None) -> list:
        """Today's practice: a random 5 % of the checked claims."""
        pool = [c for c in self.claims if c['status'] == self.STATUS['CHECKED']]
        return random.Random(seed).sample(pool, budget or self.budget)

    # ---- the learning loop
    def review(self, claim_id: str, decision: str, reviewer: str = 'Medical Officer') -> dict:
        c = self.by_id[claim_id]
        c['review'] = dict(decision=decision, reviewer=reviewer)
        delta = self.P.learn_delta if decision == 'confirm' else -self.P.learn_delta if decision == 'clear' else 0
        lo, hi = self.P.weight_bounds
        if delta:
            for r in sorted({f['rule'] for f in c['flags']}):
                frm = self.rule_weight[r]; to = min(hi, max(lo, jround(frm + delta, 1)))
                self.rule_weight[r] = to
                self.weight_log.append(dict(rule=r, from_=frm, to=to, decision=decision, claim_id=claim_id))
        return c


# ----------------------------------------------------------------------------- evaluation (evaluate.js)
def is_fraud(c: dict) -> bool:
    return c.get('truth') in FRAUD

def evaluate(eng: Engine, random_draws: int = 30) -> dict:
    ds = eng.claims
    flagged = [c for c in ds if c['flags']]; frauds = [c for c in ds if is_fraud(c)]
    tp = sum(1 for c in flagged if is_fraud(c)); fp = len(flagged) - tp; fn = len(frauds) - tp
    by_type: dict = {}
    for c in frauds:
        k = 'cross_scheme (hard: no NID + name variant)' if c['truth'] == 'cross_scheme' and (c.get('note') or '').startswith('HARD') else c['truth']
        by_type.setdefault(k, {'planted': 0, 'caught': 0}); by_type[k]['planted'] += 1
        if c['flags']: by_type[k]['caught'] += 1
    by_rule: dict = {}
    for c in flagged:
        for r in {f['rule'] for f in c['flags']}:
            by_rule.setdefault(r, {'fired': 0, 'fraud': 0}); by_rule[r]['fired'] += 1
            if is_fraud(c): by_rule[r]['fraud'] += 1
    budget = eng.budget
    ranked_frauds = sum(1 for c in sorted(flagged, key=lambda c: -c['suspicion'])[:budget] if is_fraud(c))
    pool = [c for c in ds if c['status'] == Engine.STATUS['CHECKED']]
    draws = sorted(sum(1 for c in random.Random(s).sample(pool, budget) if is_fraud(c)) for s in range(1, random_draws + 1))
    rejected = [c for c in ds if c['status'] == Engine.STATUS['REJECTED']]
    return dict(claims=len(ds), persons=len(eng.persons), frauds=len(frauds), fraud_rate=len(frauds) / len(ds),
                flagged=len(flagged), tp=tp, fp=fp, fn=fn, precision=tp / (len(flagged) or 1), recall=tp / (len(frauds) or 1),
                by_type=by_type, by_rule=by_rule, budget=budget, ranked_frauds=ranked_frauds,
                random=dict(mean=sum(draws) / len(draws), min=draws[0], max=draws[-1], draws=len(draws)),
                existing=dict(rejected=len(rejected), rejected_fraud=sum(1 for c in rejected if is_fraud(c))))

def precision_at(eng: Engine, ks=None) -> list:
    """Cumulative frauds found when a reviewer works down the ranked queue: [(k, frauds_in_top_k, precision@k)]."""
    q = eng.ranked()
    out, hits = [], 0
    for i, c in enumerate(q, 1):
        hits += is_fraud(c)
        out.append((i, hits, hits / i))
    return out

def data_path(which: str) -> str:
    """Locate a book: the local data/ copy (Week 5/ranking_notebook) or the app's backend/data (the mvp/notebook mirror)."""
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    names = {'training': ['data/claims_training.json', '../backend/data/claims.json'],
             'validation': ['data/claims_validation.json', '../backend/data/validation.json'],
             'evaluation': ['data/evaluation_from_app.json', '../backend/data/evaluation.json']}[which]
    for n in names:
        p = os.path.join(here, n)
        if os.path.exists(p): return p
    raise FileNotFoundError(f'{which} book not found near {here}')

def load_book(path: str) -> dict:
    with open(path, encoding='utf-8') as fh:
        return json.load(fh)


if __name__ == '__main__':
    import os, sys
    here = os.path.dirname(os.path.abspath(__file__))
    for name in ('training', 'validation'):
        book = load_book(data_path(name))
        e = evaluate(Engine(book))
        print(f"{name}: {e['claims']} claims · {e['frauds']} fraud · flagged {e['flagged']} · precision {100 * e['precision']:.1f} % · recall {100 * e['recall']:.1f} % "
              f"· ranked {e['ranked_frauds']} vs random {e['random']['mean']:.1f} ({e['random']['min']}–{e['random']['max']}) @ {e['budget']}")
        print('  by rule:', {r: f"{v['fired']}/{v['fraud']}" for r, v in sorted(e['by_rule'].items())})
